---
- name: Install all
  hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - wget
        - htop
        - tmux
        - nginx
        - apache2
        - gnutls-bin
        - ca-certificates
        - apt-transport-https

    - name: apache2 virtualhost on port 8888
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8888>" state=present
      notify:
        - restart apache2
    - name: apache2 listen on port 8888
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8888" state=present
      notify:
        - restart apache2
    - name: Download gpg
      get_url:
        url: https://packages.sury.org/php/apt.gpg
        dest: /etc/apt/trusted.gpg.d/php.gpg
    - name: Add php repo
      copy:
        content: "deb https://packages.sury.org/php/ stretch main"
        dest: /etc/apt/sources.list.d/php.list
    - name: Install php5.6
      apt:
        name: php5.6
        state: present
        update_cache: yes
    - name: Create nginx homedir
      file:
        path: /var/nginx
        state: directory
    - name: Create php script in nginx home
      copy:
        src: index.php
        dest: /var/nginx/index.php
    - name: Change nginx settings
      copy:
        src: default
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx
    - name: Correct php version selected
      alternatives:
        name: php
        path: /usr/bin/php5.6
    - name: Install php-fpm
      apt:
        name: php-fpm
        state: latest
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
