---
- name: Install all
  hosts: all
  become: true
  tasks:
  - name: Remove php5.6
    apt:
      name: php5.6
      state: absent
  - name: Install php7.2
    apt:
      name: php7.2
      state: present
  - name: Correct php version selected
    alternatives:
      name: php
      path: /usr/bin/php7.2
...
